language: c
dist: trusty
sudo: required
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
    - sudo apt-get install libxen-dev
    - sudo apt-get install m4
script: bash -ex travis.sh
env:
  - OCAML_VERSION=4.02
os:
  - linux
