os:
- linux
sudo: required
language: c
services:
- docker
before_install:
- docker build -t xen/ocaml .
script:
- docker run -t -v $PWD:/mnt xen/ocaml /bin/sh -c "cp -r /mnt/ . && cd mnt && jbuilder build"
